[project]
name = "oauth-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.12",
    "pydantic[email]>=2.11.5",
    "pyjwt>=2.10.1",
    "python-decouple>=3.8",
    "uvicorn>=0.34.3",
]
